### ISSUE TITLE
`bundle/` 以下のファイルが `.npmignore` で除外されている

### ISSUE THREAD

**Issue by mizar** [na2hiro/Shogi.js#32]
意図的なのかもしれませんが、ブラウザ向けのビルド `bundle/shogi-${package.version}.min.js` がnpmレジストリに含まれていないようです。

**Comment by na2hiro** [comment]
ファイルをコピーしてのブラウザでの直接読み込みの利用以外は各自バンドラ、ミニファイヤなどの利用を想定しています。

参考　https://stackoverflow.com/questions/48673408/should-javascript-npm-packages-be-minified

ただこちらにもあるようにminifiedバージョンが必要となる状況も無きにしもあらずなので含めるようにしてもいいかもしれません。その場合はファイル名からバージョン番号を落とすほうが便利そうです。
